import type { FAQItem } from "@/components/ToolFAQ";

export const hookGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Hook Generator?",
    answer: "The AI Hook Generator is a free, browser-based tool that creates attention-grabbing hooks for social media posts, YouTube videos, TikTok content, blog articles, and ad copy. It uses advanced AI (Llama 3) running directly in your browser to generate viral, scroll-stopping opening lines.",
  },
  {
    question: "Is the AI Hook Generator really free?",
    answer: "Yes, the AI Hook Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does the AI Hook Generator work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Llama 3.1 8B) directly in your web browser using WebGPU. When you enter a topic and select a platform and tone, the AI generates multiple hook variations optimized for engagement. No data is sent to any server.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. Unlike cloud-based AI tools, the AI Hook Generator runs 100% locally in your browser. Your topics, prompts, and generated hooks never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "What platforms can I generate hooks for?",
    answer: "You can generate hooks optimized for X/Twitter, LinkedIn, YouTube, TikTok, blog posts, and ad copy. Each platform has different engagement patterns, and the AI tailors its output accordingly.",
  },
  {
    question: "What tones are available for hook generation?",
    answer: "The tool offers seven distinct tones: Curiosity, Controversial, Data-Driven, Storytelling, FOMO (Fear of Missing Out), Educational, and Humorous. Each tone changes how the AI crafts your hooks to match your content strategy.",
  },
  {
    question: "Does the AI Hook Generator work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate hooks without an internet connection. The initial download is required only once.",
  },
  {
    question: "What browsers support the AI Hook Generator?",
    answer: "The tool requires a browser with WebGPU support. This includes Google Chrome 113+, Microsoft Edge 113+, and Safari 18+ (with WebGPU flags enabled). For the best experience, we recommend using the latest version of Chrome or Edge.",
  },
  {
    question: "How long does the AI model take to download?",
    answer: "The initial download of the AI model takes approximately 30-60 seconds depending on your internet speed. After that, the model is cached in your browser and loads almost instantly on subsequent visits.",
  },
  {
    question: "Can I use the generated hooks commercially?",
    answer: "Yes, all hooks generated by the AI Hook Generator are yours to use however you like - for personal projects, social media, marketing campaigns, client work, or any other commercial purpose. There are no restrictions on usage.",
  },
];

export const ctaGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Call-to-Action Generator?",
    answer: "The AI CTA Generator is a free, browser-based tool that creates high-converting call-to-action phrases for your marketing campaigns. It generates 15-20 customized CTAs for emails, ads, landing pages, and sales materials using AI running directly in your browser.",
  },
  {
    question: "Is the AI CTA Generator really free?",
    answer: "Yes, the AI CTA Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does the AI CTA Generator work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Llama 3.1 8B) directly in your web browser using WebGPU. You enter your product details, target audience, and campaign goal, and the AI generates conversion-optimized CTAs using proven marketing psychology principles. No data is sent to any server.",
  },
  {
    question: "Is my campaign data private?",
    answer: "Absolutely. Unlike cloud-based AI tools, the CTA Generator runs 100% locally in your browser. Your product details, audience information, and generated CTAs never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "What platforms can I generate CTAs for?",
    answer: "You can generate CTAs optimized for landing pages, emails, social media ads, website banners, sales emails, and lead magnets. You can also choose 'All Platforms' for versatile CTAs that work everywhere.",
  },
  {
    question: "How are the CTAs categorized?",
    answer: "Generated CTAs are automatically categorized by psychology type: Urgency (time-sensitive), Benefit (value-focused), Curiosity (intrigue-driven), Risk-Free (trust-building), and Action (direct commands). You can filter by category to find the perfect CTA.",
  },
  {
    question: "Can I export the generated CTAs?",
    answer: "Yes! Click the 'Export All' button to download all generated CTAs as a text file. You can also copy individual CTAs to your clipboard with one click.",
  },
  {
    question: "What tones are available?",
    answer: "The tool offers five tone options: Persuasive, Professional, Urgent, Friendly, and Casual. Each tone adjusts how the AI crafts your CTAs to match your brand voice and campaign style.",
  },
  {
    question: "Does the CTA Generator work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate CTAs without an internet connection.",
  },
  {
    question: "Can I use the generated CTAs commercially?",
    answer: "Yes, all CTAs generated by the tool are yours to use however you like - for personal projects, client work, marketing campaigns, ads, emails, or any other commercial purpose. There are no restrictions on usage.",
  },
];

export const coverLetterGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Cover Letter Generator?",
    answer: "The AI Cover Letter Generator is a free, browser-based tool that creates personalized, professional cover letters tailored to specific job postings. It uses advanced AI (Llama 3) running directly in your browser to generate ATS-optimized cover letters in about 30 seconds.",
  },
  {
    question: "Is the AI Cover Letter Generator really free?",
    answer: "Yes, the AI Cover Letter Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you. No signup or credit card required.",
  },
  {
    question: "How does the AI Cover Letter Generator work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Llama 3.1 8B) directly in your web browser using WebGPU. You enter your job details, background, and preferences, and the AI generates a personalized, professionally formatted cover letter. No data is sent to any server.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. Job search data is highly sensitive, and unlike cloud-based AI tools, the Cover Letter Generator runs 100% locally in your browser. Your job details, personal information, and generated cover letters never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "What information do I need to provide?",
    answer: "To generate the best cover letter, you should provide the job title, company name, your name, current job title, years of experience, key skills and achievements, and why you want the job. You can also optionally include the job description and company info for more personalized results.",
  },
  {
    question: "Are the generated cover letters ATS-optimized?",
    answer: "Yes. The AI is trained to produce cover letters that follow ATS (Applicant Tracking System) best practices, including proper formatting, relevant keyword usage, and standard business letter structure. This helps ensure your application gets past automated screening systems.",
  },
  {
    question: "Can I edit the generated cover letter?",
    answer: "Yes! After generation, you can toggle edit mode to make changes directly in your browser. You can also copy the letter to your clipboard or download it as a text file to continue editing in your preferred word processor.",
  },
  {
    question: "Can I save multiple cover letters?",
    answer: "Yes, you can save up to 10 cover letter drafts in your browser's local storage. Each draft is saved with the job title and company name for easy reference. Your saved drafts persist between sessions and are stored only on your device.",
  },
  {
    question: "Does the Cover Letter Generator work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate cover letters without an internet connection. The initial download is required only once.",
  },
  {
    question: "Can I use the generated cover letters for real job applications?",
    answer: "Yes, all cover letters generated by the tool are yours to use for any job application. We recommend reviewing and personalizing the output to ensure it accurately reflects your experience. The AI provides a strong professional foundation that you can refine to perfectly match your voice.",
  },
];

export const defaultToolFAQs: FAQItem[] = [
  {
    question: "Is this AI tool really free?",
    answer: "Yes, all Browser AI Tools are completely free. The AI runs locally in your browser, so there are no server costs. No subscriptions, no hidden fees, no usage limits.",
  },
  {
    question: "How does browser-based AI work?",
    answer: "We use WebLLM technology to run AI models directly in your browser using WebGPU. This means your data never leaves your device - everything is processed locally for maximum privacy.",
  },
  {
    question: "What browsers are supported?",
    answer: "You need a browser with WebGPU support: Google Chrome 113+, Microsoft Edge 113+, or Safari 18+ with WebGPU flags enabled. We recommend the latest version of Chrome or Edge for the best experience.",
  },
  {
    question: "Does this tool work offline?",
    answer: "Yes! After the AI model is downloaded on first use, it's cached in your browser. You can then use the tool without an internet connection.",
  },
  {
    question: "Is my data private?",
    answer: "Absolutely. Unlike cloud-based AI tools, Browser AI Tools runs 100% locally in your browser. Your inputs and outputs never leave your device. No servers, no tracking, no data collection.",
  },
];
