import type { FAQItem } from "@/components/ToolFAQ";

export const hookGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Hook Generator?",
    answer: "The AI Hook Generator is a free, browser-based tool that creates attention-grabbing hooks for social media posts, YouTube videos, TikTok content, blog articles, and ad copy. It uses advanced AI (Qwen 2.5) running directly in your browser to generate viral, scroll-stopping opening lines.",
  },
  {
    question: "Is the AI Hook Generator really free?",
    answer: "Yes, the AI Hook Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does the AI Hook Generator work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Qwen 2.5 1.5B) directly in your web browser using WebGPU. When you enter a topic and select a platform and tone, the AI generates multiple hook variations optimized for engagement. No data is sent to any server.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. Unlike cloud-based AI tools, the AI Hook Generator runs 100% locally in your browser. Your topics, prompts, and generated hooks never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "What platforms can I generate hooks for?",
    answer: "You can generate hooks optimized for X/Twitter, LinkedIn, YouTube, TikTok, blog posts, and ad copy. Each platform has different engagement patterns, and the AI tailors its output accordingly.",
  },
  {
    question: "What tones are available for hook generation?",
    answer: "The tool offers seven distinct tones: Curiosity, Controversial, Data-Driven, Storytelling, FOMO (Fear of Missing Out), Educational, and Humorous. Each tone changes how the AI crafts your hooks to match your content strategy.",
  },
  {
    question: "Does the AI Hook Generator work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate hooks without an internet connection. The initial download is required only once.",
  },
  {
    question: "What browsers support the AI Hook Generator?",
    answer: "The tool requires a browser with WebGPU support. This includes Google Chrome 113+, Microsoft Edge 113+, and Safari 18+ (with WebGPU flags enabled). For the best experience, we recommend using the latest version of Chrome or Edge.",
  },
  {
    question: "How long does the AI model take to download?",
    answer: "The initial download of the AI model takes approximately 30-60 seconds depending on your internet speed. After that, the model is cached in your browser and loads almost instantly on subsequent visits.",
  },
  {
    question: "Can I use the generated hooks commercially?",
    answer: "Yes, all hooks generated by the AI Hook Generator are yours to use however you like - for personal projects, social media, marketing campaigns, client work, or any other commercial purpose. There are no restrictions on usage.",
  },
];

export const ctaGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Call-to-Action Generator?",
    answer: "The AI CTA Generator is a free, browser-based tool that creates high-converting call-to-action phrases for your marketing campaigns. It generates 15-20 customized CTAs for emails, ads, landing pages, and sales materials using AI running directly in your browser.",
  },
  {
    question: "Is the AI CTA Generator really free?",
    answer: "Yes, the AI CTA Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does the AI CTA Generator work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Qwen 2.5 1.5B) directly in your web browser using WebGPU. You enter your product details, target audience, and campaign goal, and the AI generates conversion-optimized CTAs using proven marketing psychology principles. No data is sent to any server.",
  },
  {
    question: "Is my campaign data private?",
    answer: "Absolutely. Unlike cloud-based AI tools, the CTA Generator runs 100% locally in your browser. Your product details, audience information, and generated CTAs never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "What platforms can I generate CTAs for?",
    answer: "You can generate CTAs optimized for landing pages, emails, social media ads, website banners, sales emails, and lead magnets. You can also choose 'All Platforms' for versatile CTAs that work everywhere.",
  },
  {
    question: "How are the CTAs categorized?",
    answer: "Generated CTAs are automatically categorized by psychology type: Urgency (time-sensitive), Benefit (value-focused), Curiosity (intrigue-driven), Risk-Free (trust-building), and Action (direct commands). You can filter by category to find the perfect CTA.",
  },
  {
    question: "Can I export the generated CTAs?",
    answer: "Yes! Click the 'Export All' button to download all generated CTAs as a text file. You can also copy individual CTAs to your clipboard with one click.",
  },
  {
    question: "What tones are available?",
    answer: "The tool offers five tone options: Persuasive, Professional, Urgent, Friendly, and Casual. Each tone adjusts how the AI crafts your CTAs to match your brand voice and campaign style.",
  },
  {
    question: "Does the CTA Generator work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate CTAs without an internet connection.",
  },
  {
    question: "Can I use the generated CTAs commercially?",
    answer: "Yes, all CTAs generated by the tool are yours to use however you like - for personal projects, client work, marketing campaigns, ads, emails, or any other commercial purpose. There are no restrictions on usage.",
  },
];

export const coverLetterGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Cover Letter Generator?",
    answer: "The AI Cover Letter Generator is a free, browser-based tool that creates personalized, professional cover letters tailored to specific job postings. It uses advanced AI (Qwen 2.5) running directly in your browser to generate ATS-optimized cover letters in about 30 seconds.",
  },
  {
    question: "Is the AI Cover Letter Generator really free?",
    answer: "Yes, the AI Cover Letter Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you. No signup or credit card required.",
  },
  {
    question: "How does the AI Cover Letter Generator work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Qwen 2.5 1.5B) directly in your web browser using WebGPU. You enter your job details, background, and preferences, and the AI generates a personalized, professionally formatted cover letter. No data is sent to any server.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. Job search data is highly sensitive, and unlike cloud-based AI tools, the Cover Letter Generator runs 100% locally in your browser. Your job details, personal information, and generated cover letters never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "What information do I need to provide?",
    answer: "To generate the best cover letter, you should provide the job title, company name, your name, current job title, years of experience, key skills and achievements, and why you want the job. You can also optionally include the job description and company info for more personalized results.",
  },
  {
    question: "Are the generated cover letters ATS-optimized?",
    answer: "Yes. The AI is trained to produce cover letters that follow ATS (Applicant Tracking System) best practices, including proper formatting, relevant keyword usage, and standard business letter structure. This helps ensure your application gets past automated screening systems.",
  },
  {
    question: "Can I edit the generated cover letter?",
    answer: "Yes! After generation, you can toggle edit mode to make changes directly in your browser. You can also copy the letter to your clipboard or download it as a text file to continue editing in your preferred word processor.",
  },
  {
    question: "Can I save multiple cover letters?",
    answer: "Yes, you can save up to 10 cover letter drafts in your browser's local storage. Each draft is saved with the job title and company name for easy reference. Your saved drafts persist between sessions and are stored only on your device.",
  },
  {
    question: "Does the Cover Letter Generator work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate cover letters without an internet connection. The initial download is required only once.",
  },
  {
    question: "Can I use the generated cover letters for real job applications?",
    answer: "Yes, all cover letters generated by the tool are yours to use for any job application. We recommend reviewing and personalizing the output to ensure it accurately reflects your experience. The AI provides a strong professional foundation that you can refine to perfectly match your voice.",
  },
];

export const startupNameGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Startup Name Generator?",
    answer: "The AI Startup Name Generator is a free, browser-based tool that creates creative, brandable startup names. It generates 10+ unique name ideas with meanings, categories, and analysis using advanced AI (Qwen 2.5) running directly in your browser.",
  },
  {
    question: "Is it really free?",
    answer: "Yes, the AI Startup Name Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does it work?",
    answer: "The tool uses WebLLM technology to run an AI language model (Qwen 2.5 1.5B) directly in your web browser using WebGPU. You describe your startup, select an industry, choose naming styles and preferences, and the AI generates creative names with meanings and analysis. No data is sent to any server.",
  },
  {
    question: "Is my startup idea private?",
    answer: "Absolutely. Unlike cloud-based AI tools, the Startup Name Generator runs 100% locally in your browser. Your startup description, industry, and preferences never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "How many names does it generate?",
    answer: "The tool generates 10+ startup name ideas in each generation. Each name includes the category (compound, invented, descriptive, etc.), a meaningful definition, and analysis of why it works for your startup.",
  },
  {
    question: "Are the names unique and not already trademarked?",
    answer: "The AI is trained to generate creative and original names, but we cannot guarantee that names are trademark-free or not already in use. We recommend checking the USPTO trademark database and domain registrars for your selected names. The tool includes a domain availability estimator based on name characteristics to help guide your choices.",
  },
  {
    question: "Can I check domain availability directly?",
    answer: "The tool provides a domain availability estimator that uses heuristics to predict whether a domain is likely available, possibly available, or likely taken. For definitive checks, you can use domain registrars like GoDaddy, Namecheap, or Google Domains to verify availability.",
  },
  {
    question: "What naming styles are supported?",
    answer: "The tool supports six naming style categories: Compound Words (e.g., Dropbox, YouTube), Invented (e.g., Spotify, Kodak), Descriptive (e.g., Shopify, Salesforce), Portmanteau (e.g., Instagram, Pinterest), Single Word (e.g., Stripe, Uber), and Metaphorical (e.g., Amazon, Apple).",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate startup names without an internet connection. The initial download is required only once.",
  },
  {
    question: "Can I use the generated names for my real business?",
    answer: "Yes, all names generated by the AI Startup Name Generator are yours to use however you like - for real startups, business proposals, side projects, or any other commercial purpose. There are no restrictions on usage. However, we recommend conducting trademark searches and domain checks before finalizing your business name.",
  },
];

export const businessIdeaGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Business Idea Generator?",
    answer: "The AI Business Idea Generator is a free, browser-based tool that creates personalized, viable business ideas tailored to your skills, budget, and interests. It generates 15+ validated business ideas with viability scores, action plans, revenue models, and detailed analysis using advanced AI (Qwen 2.5) running directly in your browser.",
  },
  {
    question: "Is it really free?",
    answer: "Yes, the AI Business Idea Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does the AI generate business ideas?",
    answer: "The tool uses WebLLM technology to run an AI language model (Qwen 2.5 1.5B) directly in your web browser using WebGPU. You provide your skills, interests, budget, and preferences, and the AI generates personalized business ideas with detailed validation, scoring, and action plans. No data is sent to any server.",
  },
  {
    question: "Is my information private?",
    answer: "Absolutely. Unlike cloud-based AI tools, the Business Idea Generator runs 100% locally in your browser. Your skills, interests, budget details, and generated ideas never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "How many business ideas does it generate?",
    answer: "The tool generates 15+ unique business ideas per generation. Each idea includes a viability score, startup cost estimate, time to launch, potential monthly revenue, difficulty level, and detailed analysis including target market, revenue model, and action steps.",
  },
  {
    question: "Are the viability scores accurate?",
    answer: "The viability scores are AI-generated estimates based on market research principles, startup metrics, and feasibility analysis. While they provide valuable guidance, we recommend conducting your own due diligence, market research, and validation before launching any business. Use the scores as a starting point for further investigation.",
  },
  {
    question: "Can I use these ideas to start a real business?",
    answer: "Yes! The generated ideas are designed to be actionable and realistic. Many are based on proven business models with low barriers to entry. We recommend validating your chosen idea by researching the market, talking to potential customers, and testing a minimum viable product (MVP) before fully committing.",
  },
  {
    question: "What makes this different from other idea generators?",
    answer: "This tool combines personalization (based on your specific skills and budget), viability scoring (realistic assessments), and actionable plans (next steps to validate). Unlike generic idea lists, it tailors suggestions to your situation and includes detailed metrics and reasoning. Plus, it's 100% private and runs entirely in your browser.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate business ideas without an internet connection. The initial download is required only once.",
  },
  {
    question: "How are the startup costs and revenue estimates calculated?",
    answer: "The AI generates cost and revenue estimates based on industry benchmarks, business model type, and the scope of your specific idea. Estimates are educated projections, not guarantees. Actual costs and revenue will vary significantly based on execution, market conditions, marketing effectiveness, and your operational efficiency. Always validate with real market data.",
  },
];

export const keywordGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Keyword Generator?",
    answer: "The AI Keyword Generator is a free, browser-based tool that generates high-value SEO keywords for your content strategy. It produces 25-100 keyword ideas organized by topic clusters, with search volume estimates, keyword difficulty scores, search intent classification, and CPC estimates—all using advanced AI (Qwen 2.5) running directly in your browser.",
  },
  {
    question: "Is it really free?",
    answer: "Yes, the AI Keyword Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How does the AI generate keywords?",
    answer: "The tool uses WebLLM technology to run an AI language model (Qwen 2.5 1.5B) directly in your web browser using WebGPU. You enter a seed keyword or topic, select your industry and content type, and the AI generates relevant keywords organized by semantic clusters with detailed metrics. No data is sent to any server.",
  },
  {
    question: "Is my data private?",
    answer: "Absolutely. Unlike cloud-based keyword research tools, the AI Keyword Generator runs 100% locally in your browser. Your seed keywords, industry selection, and generated keyword data never leave your device. There's no server processing, no data collection, and no tracking.",
  },
  {
    question: "How many keywords does it generate?",
    answer: "By default, the tool generates 50 keyword ideas, but you can customize this from 25 to 100 keywords in the advanced options. Keywords are automatically organized into semantic clusters by topic for easier categorization and strategy planning.",
  },
  {
    question: "Are the search volume estimates accurate?",
    answer: "The search volume estimates are AI-generated projections based on keyword characteristics, search patterns, and industry benchmarks. They provide valuable relative guidance for keyword prioritization, but we recommend validating with professional SEO tools like SEMrush or Ahrefs for exact search volume data before launching campaigns.",
  },
  {
    question: "What is keyword difficulty?",
    answer: "Keyword difficulty (scored 0-100) is a metric that estimates how hard it would be to rank for a keyword. Low difficulty (0-33) keywords are easier to rank for, Medium (34-66) require moderate effort, and High (67-100) are highly competitive. Focus on low-to-medium difficulty keywords when starting out.",
  },
  {
    question: "Can I export the keywords?",
    answer: "Yes! You can export all generated keywords as a CSV file with columns for keyword, intent, search volume, difficulty, and CPC estimate. This makes it easy to import into spreadsheets, SEO tools, or content planning documents.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate keywords without an internet connection. The initial download is required only once.",
  },
  {
    question: "Can I use these keywords commercially?",
    answer: "Yes, all keywords generated by the AI Keyword Generator are yours to use however you like—for personal projects, client work, content strategy, SEO campaigns, or any commercial purpose. There are no restrictions on usage.",
  },
];

export const hashtagGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Hashtag Generator?",
    answer: "The AI Hashtag Generator is a free, browser-based tool that creates optimized hashtag sets for Instagram, TikTok, LinkedIn, and Twitter/X. It uses AI (Qwen 2.5) running directly in your browser to generate platform-specific hashtag strategies with volume categorization, strategy notes, and copy-paste ready sets.",
  },
  {
    question: "Is the AI Hashtag Generator really free?",
    answer: "Yes, the AI Hashtag Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How many hashtags does it generate?",
    answer: "The number depends on the platform: Instagram gets up to 30 hashtags (the platform maximum), TikTok gets 5-8, LinkedIn gets 3-5, and Twitter gets 1-2. You can generate for multiple platforms at once, getting optimized sets for each.",
  },
  {
    question: "How does it categorize hashtags by volume?",
    answer: "Hashtags are organized into categories: High-Volume (500k-5M posts) for maximum reach, Medium-Volume (50k-500k posts) for the sweet spot of competition vs. discoverability, Niche/Low-Volume (1k-50k posts) for targeted engagement, plus Trending, Community, and Branded categories.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. Unlike cloud-based tools, the AI Hashtag Generator runs 100% locally in your browser. Your content descriptions, generated hashtags, and saved sets never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "Can I save and reuse hashtag sets?",
    answer: "Yes! You can favorite individual hashtags, copy entire sets with one click, and export all hashtags as a CSV file. Your generation history is saved locally in your browser for easy reference.",
  },
  {
    question: "Does it work for all social media platforms?",
    answer: "The tool currently supports Instagram, TikTok, LinkedIn, and Twitter/X with platform-specific strategies. Each platform has different optimal hashtag counts and strategies, and the tool adapts its output accordingly.",
  },
  {
    question: "How does account size affect the hashtags?",
    answer: "Smaller accounts benefit from more niche, lower-competition hashtags where they can rank in top posts. Larger accounts can compete with high-volume hashtags. The tool adjusts the hashtag mix based on your selected account size to optimize for your reach potential.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate hashtags without an internet connection.",
  },
  {
    question: "Can I use these hashtags commercially?",
    answer: "Yes, all hashtags generated by the AI Hashtag Generator are yours to use however you like -- for personal accounts, client work, brand campaigns, or any commercial purpose. There are no restrictions on usage.",
  },
];

export const tiktokCaptionGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI TikTok Caption Generator?",
    answer: "The AI TikTok Caption Generator is a free, browser-based tool that creates viral-optimized TikTok captions with hooks, calls-to-action, strategic hashtags, and engagement triggers. It uses AI (Qwen 2.5) running directly in your browser to generate platform-native captions tailored to your content, niche, and goals.",
  },
  {
    question: "Is the AI TikTok Caption Generator really free?",
    answer: "Yes, the AI TikTok Caption Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs to pass on to you.",
  },
  {
    question: "How many caption variations does it generate?",
    answer: "By default, the tool generates 5 unique caption variations, each with a different angle (curiosity hook, relatable/funny, educational, question-based, bold statement). You can adjust this from 3 to 7 variations in the Advanced Options.",
  },
  {
    question: "How does it optimize for the FYP (For You Page)?",
    answer: "The AI uses proven TikTok caption formulas and hook strategies that are known to perform well with TikTok's algorithm. It creates captions with strong opening hooks (the first 3 words are critical), engagement triggers that boost comments, and strategic hashtag placement -- all factors that influence FYP distribution.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. Unlike cloud-based tools, the AI TikTok Caption Generator runs 100% locally in your browser. Your video descriptions, generated captions, and saved content never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "What are first comment suggestions?",
    answer: "First comment suggestions are strategic comments you can pin to your own video immediately after posting. They boost early engagement (which the algorithm loves), provide additional context, tease upcoming content, or ask questions that encourage viewers to comment.",
  },
  {
    question: "Can I customize the tone and style?",
    answer: "Yes! You can select 1-2 tones from options like Casual, Funny, Inspiring, Educational, Relatable, Hype/Energetic, Mysterious, and Storytelling. You can also choose caption length (short, medium, long) and configure hashtag count, emoji usage, and trending format preferences.",
  },
  {
    question: "Does it include hashtags?",
    answer: "Yes, by default the tool includes 5 strategic hashtags with each caption. You can adjust the number (3-8) or disable hashtags entirely in Advanced Options. The hashtags follow TikTok best practices with a mix of trending, niche-specific, and content descriptor tags.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate TikTok captions without an internet connection.",
  },
  {
    question: "Can I use these captions commercially?",
    answer: "Yes, all captions generated by the AI TikTok Caption Generator are yours to use however you like -- for personal accounts, brand pages, client work, or any commercial purpose. There are no restrictions on usage.",
  },
];

export const linkedInPostGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI LinkedIn Post Generator?",
    answer: "The AI LinkedIn Post Generator is a free, browser-based tool that creates professional, engagement-optimized LinkedIn posts. It uses AI (Qwen 2.5) running directly in your browser to generate thought leadership content with hooks, formatting, hashtags, and calls-to-action tailored to your topic, audience, and goals.",
  },
  {
    question: "Is the AI LinkedIn Post Generator really free?",
    answer: "Yes, the AI LinkedIn Post Generator is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs.",
  },
  {
    question: "What post types can it generate?",
    answer: "The tool supports six post types: Value/Advice Posts (actionable tips and lessons), Story Posts (personal or professional narratives), Insight/Opinion Posts (industry perspectives), Question Posts (discussion prompts), Announcement Posts (career updates and milestones), and List Posts (numbered tips or resources). Each type follows a different structure optimized for its purpose.",
  },
  {
    question: "How does it optimize for LinkedIn engagement?",
    answer: "The AI creates posts with strong opening hooks (the first 3 lines are critical since they appear before the 'see more' button), professional formatting with short paragraphs and line breaks, strategic calls-to-action that drive comments, and 3-5 relevant hashtags. It also provides first comment suggestions for an algorithm boost.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. The AI LinkedIn Post Generator runs 100% locally in your browser. Your post topics, generated content, and saved drafts never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "Can I generate multiple versions for A/B testing?",
    answer: "Yes! By default, the tool generates 2 versions of your post with different hooks and structures. You can adjust this from 1 to 3 versions in the Advanced Options. This lets you test which approach resonates best with your audience.",
  },
  {
    question: "What's the first comment strategy?",
    answer: "The tool generates a suggested first comment to post immediately after publishing. LinkedIn's algorithm prioritizes posts with early engagement, so posting a strategic first comment (with additional context, a question, or a link) helps boost your post's distribution.",
  },
  {
    question: "How many hashtags should I use on LinkedIn?",
    answer: "LinkedIn best practice is 3-5 hashtags placed at the end of your post. The tool defaults to 3 hashtags with a mix of one broad industry tag, one medium-reach tag, and one niche tag. You can adjust the count in Advanced Options.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate LinkedIn posts without an internet connection.",
  },
  {
    question: "Can I use these posts commercially?",
    answer: "Yes, all posts generated by the AI LinkedIn Post Generator are yours to use however you like -- for personal branding, client work, company pages, or any commercial purpose. There are no restrictions on usage.",
  },
];

export const toneConverterFAQs: FAQItem[] = [
  {
    question: "What is the AI Tone Converter?",
    answer: "The AI Tone Converter is a free, browser-based tool that transforms the tone of your written text while preserving its core message. It uses AI (Qwen 2.5) running directly in your browser to convert between 10+ tones including professional, casual, friendly, formal, persuasive, empathetic, confident, apologetic, enthusiastic, and direct.",
  },
  {
    question: "Is the AI Tone Converter really free?",
    answer: "Yes, the AI Tone Converter is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs.",
  },
  {
    question: "What tones can it convert between?",
    answer: "The tool supports 10 target tones: Professional (business-appropriate), Casual (relaxed and conversational), Friendly (warm and approachable), Formal (traditional and diplomatic), Persuasive (compelling and action-oriented), Empathetic (understanding and compassionate), Confident (assertive and authoritative), Apologetic (remorseful and solution-focused), Enthusiastic (energetic and positive), and Direct (straightforward and concise).",
  },
  {
    question: "Does it preserve my original message?",
    answer: "Yes. The AI Tone Converter changes the tone -- vocabulary, sentence structure, formality level, and emotional coloring -- while keeping the core message, facts, and key information intact. You can also specify key phrases to keep unchanged.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. The AI Tone Converter runs 100% locally in your browser. Your text and converted versions never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "Can I compare the original and converted text?",
    answer: "Yes! The tool offers a side-by-side view where you can see your original text next to the converted version. It also provides a detailed 'What Changed' analysis showing specific vocabulary swaps, sentence structure changes, and tone shifts.",
  },
  {
    question: "Can it generate alternative versions?",
    answer: "Yes. By default, the tool generates both a primary conversion and an alternative version with a slightly different approach to the same tone. This lets you choose the version that best fits your context.",
  },
  {
    question: "What types of text can I convert?",
    answer: "You can convert any written text up to 2,000 characters -- emails, messages, feedback, proposals, apologies, announcements, social media posts, customer service responses, or any other written communication.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can convert text tones without an internet connection.",
  },
  {
    question: "Can I use converted text commercially?",
    answer: "Yes, all text generated by the AI Tone Converter is yours to use however you like -- for business emails, client communication, marketing, customer service, or any commercial purpose. There are no restrictions on usage.",
  },
];

export const interviewAnswerGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Interview Answer Generator?",
    answer: "The AI Interview Answer Generator is a free, browser-based tool that creates professional interview answers using the STAR method (Situation, Task, Action, Result). It uses AI (Qwen 2.5) running directly in your browser to generate structured, compelling answers tailored to your specific question, job role, and experience level.",
  },
  {
    question: "What is the STAR method?",
    answer: "STAR stands for Situation, Task, Action, Result. It is a proven framework for structuring behavioral interview answers. You describe the Situation (context), your Task (responsibility), the Actions you took, and the Results you achieved. This structure helps you deliver clear, organized, and impactful answers.",
  },
  {
    question: "Is the AI Interview Answer Generator really free?",
    answer: "Yes, it is completely free with no hidden costs, subscriptions, or usage limits. The AI model runs locally in your browser, so there are no server costs.",
  },
  {
    question: "What types of interview questions can it handle?",
    answer: "The tool handles behavioral questions ('Tell me about a time when...'), situational questions ('What would you do if...'), strength and weakness questions, 'Tell me about yourself,' 'Why should we hire you,' and many more. It adapts the answer structure based on the question type.",
  },
  {
    question: "Is my data private when using this tool?",
    answer: "Absolutely. The AI Interview Answer Generator runs 100% locally in your browser. Your interview questions, job details, and generated answers never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "How does it customize answers for my experience level?",
    answer: "The tool adjusts answer complexity, vocabulary, and framing based on your experience level -- entry-level (0-2 years), mid-level (3-5 years), senior (6-10 years), executive (10+ years), or career changer. Entry-level answers focus on transferable skills and potential, while executive answers emphasize strategic impact and leadership.",
  },
  {
    question: "What are the delivery tips?",
    answer: "The tool provides specific guidance on how to deliver your answer effectively, including body language tips (eye contact, posture, gestures), tone and pacing advice (speaking speed, emphasis, pauses), and engagement strategies (reading interviewer reactions, knowing when to elaborate or wrap up).",
  },
  {
    question: "Can I save answers for practice?",
    answer: "Yes! You can save answers to your local library, favorite specific answers, and build a collection of prepared responses for different question types. All data is stored in your browser's local storage.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser's storage. Once downloaded, you can generate interview answers without an internet connection.",
  },
  {
    question: "Can I use these answers in real interviews?",
    answer: "Yes, but we recommend using the generated answers as a starting point and personalizing them with your own specific experiences and details. The best interview answers sound natural, not memorized. Practice delivering the key points in your own words rather than reciting the generated text word-for-word.",
  },
];

export const resumeBulletGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Resume Bullet Generator?",
    answer: "The AI Resume Bullet Generator is a free, browser-based tool that creates powerful, ATS-optimized resume bullet points from your work experience. It uses AI (Qwen 2.5) running locally in your browser to generate achievement-focused bullets with quantified results, strong action verbs, and industry-specific keywords.",
  },
  {
    question: "What is the CAR method for resume bullets?",
    answer: "CAR stands for Context-Action-Result. Context describes the situation or challenge, Action describes what you specifically did (starting with a strong verb), and Result shows the measurable outcome. This structure transforms bland job descriptions into compelling achievement statements that demonstrate your value to employers.",
  },
  {
    question: "What does ATS-optimized mean?",
    answer: "ATS (Applicant Tracking System) is software that scans resumes before a human recruiter sees them. Up to 75% of resumes are rejected by ATS. Our tool generates bullets that are ATS-friendly by using standard formatting, industry keywords, and avoiding special characters that confuse parsing systems.",
  },
  {
    question: "Is the Resume Bullet Generator free?",
    answer: "Yes, completely free with no hidden costs, usage limits, or subscriptions. The AI runs locally in your browser, so there are no server costs to pass on to users.",
  },
  {
    question: "How does experience level affect the bullets?",
    answer: "The tool adjusts action verb strength and framing based on your level. Entry-level uses verbs like 'Coordinated' and 'Assisted,' mid-level uses 'Managed' and 'Implemented,' and senior/executive level uses 'Spearheaded' and 'Orchestrated.' The complexity of achievements and scope also scales accordingly.",
  },
  {
    question: "Is my resume data private?",
    answer: "Yes. The AI Resume Bullet Generator runs 100% locally in your browser. Your job history, achievements, and generated bullets never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "What if I don't have specific metrics?",
    answer: "The tool can generate reasonable estimates and comparative metrics even without exact numbers. However, specific numbers make bullets significantly more powerful. Try to recall approximate percentages, dollar amounts, team sizes, or timeframes -- even estimates like 'approximately 30%' are more compelling than no numbers at all.",
  },
  {
    question: "Can I use these bullets on my actual resume?",
    answer: "Yes! The bullets are designed to be copy-paste ready for your resume. We recommend reviewing and personalizing them with your specific details -- the more accurate and specific the information you provide, the more ready-to-use the output will be.",
  },
  {
    question: "Does it work for career changers?",
    answer: "Yes. Select 'Career Changer' as your experience level, and the tool will focus on transferable skills, highlight relevant achievements from your previous field, and frame your experience in terms that resonate with your target industry.",
  },
  {
    question: "How many bullet points should I have per job?",
    answer: "Most resume experts recommend 3-5 bullet points per position. Lead with your strongest, most relevant achievement. For your most recent role, you can include up to 6-7 bullets. For older positions, 2-3 is sufficient. Quality always trumps quantity.",
  },
];

export const blogOutlineGeneratorFAQs: FAQItem[] = [
  {
    question: "What is the AI Blog Outline Generator?",
    answer: "The AI Blog Outline Generator is a free, browser-based tool that creates comprehensive, SEO-optimized blog post outlines. It generates title options, meta descriptions, introduction structure, H2/H3 sections with content guidance, conclusion, and FAQ suggestions -- all powered by AI running locally in your browser.",
  },
  {
    question: "How does the outline help with SEO?",
    answer: "The tool plans keyword placement in titles, headings, and section content. It structures your post with proper H2/H3 hierarchy that search engines reward, suggests meta descriptions optimized for click-through rates, and includes content depth that helps rank for featured snippets.",
  },
  {
    question: "What content types are supported?",
    answer: "The tool supports 8 content types: How-To Guides, Listicles, Ultimate Guides, Comparison articles, Reviews, Opinion pieces, Case Studies, and News/Trend Analysis. Each type generates a different outline structure optimized for that format.",
  },
  {
    question: "Is the Blog Outline Generator free?",
    answer: "Yes, completely free with no hidden costs, usage limits, or subscriptions. The AI runs locally in your browser, so there are no server costs.",
  },
  {
    question: "Is my content private?",
    answer: "Yes. The AI Blog Outline Generator runs 100% locally in your browser. Your topics, keywords, and generated outlines never leave your device. There is no server processing, no data collection, and no tracking.",
  },
  {
    question: "How do I use the word count slider?",
    answer: "The word count slider sets your target post length from 500 to 5,000 words. The tool automatically adjusts the number of sections and content depth based on your target. Shorter posts get fewer sections with focused content, while longer posts get more comprehensive outlines with additional subsections.",
  },
  {
    question: "Can I export the outline?",
    answer: "You can copy the entire outline or individual sections to your clipboard. Use the Copy All button to get the complete outline in a structured format that works in any text editor, Google Docs, or writing tool.",
  },
  {
    question: "What are the tone options?",
    answer: "You can select one or more tones: Professional, Conversational, Educational, Entertaining, or Authoritative. Combining tones (like Professional + Conversational) gives you a balanced style. The tone affects word choice, content approach, and engagement strategies in the outline.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser. Once downloaded, you can generate blog outlines without an internet connection.",
  },
  {
    question: "How many sections does it generate?",
    answer: "The number of sections scales with your target word count -- roughly one H2 section per 300-350 words. A 1,500-word post gets about 4-5 sections, while a 3,000-word comprehensive guide gets 8-10 sections, each with its own H3 subsections.",
  },
];

export const documentAnalyzerFAQs: FAQItem[] = [
  {
    question: "Is my document really private?",
    answer: "Yes, 100%. Your document is processed entirely in your browser using WebLLM technology. The text is extracted locally using PDF.js and analyzed by an AI model running on your device's GPU. No data is ever uploaded to any server. This makes it safe for confidential documents, legal contracts, medical records, and proprietary business information.",
  },
  {
    question: "What file types are supported?",
    answer: "The tool currently supports PDF files (.pdf) and plain text files (.txt). You can also paste any text directly -- from articles, emails, web pages, or any other source. Support for .docx files is planned for a future update.",
  },
  {
    question: "How long can my document be?",
    answer: "You can upload or paste documents up to 200,000 characters (roughly 50 pages). For AI analysis, the tool processes the first ~4,000 characters to generate insights, which typically covers the most important content. Longer documents are truncated for analysis but fully stored in your browser.",
  },
  {
    question: "What analysis options are available?",
    answer: "You can choose from seven analysis modes: Full Summary (2-4 paragraph overview), Key Insights (bullet-point takeaways), Simplified Explanation (ELI5 mode for complex topics), Important Quotes (notable excerpts), Key Statistics (numbers and data points), Action Items (next steps), and Study Questions (exam or interview prep). Select one or more modes for your analysis.",
  },
  {
    question: "Can I use this for research papers?",
    answer: "Absolutely. The tool is designed for academic documents. Set the document type to 'Research Paper' and choose analysis modes like Key Insights, Important Quotes, and Study Questions. Use the College or Professional reading level for appropriate depth.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser. Once downloaded, you can analyze documents without an internet connection. Your analyses are also saved locally so you can review them anytime.",
  },
  {
    question: "How accurate is the analysis?",
    answer: "The AI is instructed to maintain strict factual fidelity to the source document and never add information not present in the text. However, as with any AI tool, we recommend reviewing the output against the original document for critical use cases like legal or medical analysis.",
  },
  {
    question: "Can I analyze multiple documents?",
    answer: "You can analyze documents one at a time. Each analysis is saved to your browser's local storage, so you can build a library of analyzed documents. Document comparison (analyzing two documents side by side) is planned for a future update.",
  },
];

export const messageAnalyzerFAQs: FAQItem[] = [
  {
    question: "Can anyone see the messages I analyze?",
    answer: "No. Your messages are processed entirely in your browser using WebLLM technology. The AI model runs on your device's GPU -- nothing is ever sent to any server. Not even we can see what you analyze. This makes it safe for private texts, work emails, dating messages, and sensitive conversations.",
  },
  {
    question: "What types of messages can I analyze?",
    answer: "You can analyze any text-based message: texts, emails, DMs, Slack messages, dating app conversations, work emails, suspicious messages, or any other digital communication. Just paste the message into the text area and select your analysis options.",
  },
  {
    question: "How accurate is the tone and intent analysis?",
    answer: "The AI provides well-reasoned interpretations based on common communication patterns, linguistics, and psychology. However, text communication lacks body language and vocal tone, so interpretations are informed guesses rather than certainties. The tool provides confidence levels and multiple possible interpretations when a message is ambiguous.",
  },
  {
    question: "Can it detect scams and phishing?",
    answer: "Yes. The Scam Detection mode checks for common phishing indicators like urgency tactics, suspicious links, impersonation attempts, requests for sensitive information, and too-good-to-be-true offers. It provides a risk level assessment and recommended actions. However, always exercise your own judgment for critical decisions.",
  },
  {
    question: "What are the analysis modes available?",
    answer: "There are 7 analysis modes: Tone Analysis (detect emotional tone), Intent Analysis (what they really mean), Reply Suggestions (3 response options in different tones), Red Flags Check (manipulation, gaslighting indicators), Relationship Insights (interest level, commitment signals), Professional Analysis (workplace communication), and Scam Detection (phishing and fraud checks). You can select any combination.",
  },
  {
    question: "Does it work for dating and relationship messages?",
    answer: "Absolutely. The Relationship Insights mode is specifically designed for dating and personal communication. It analyzes interest level, enthusiasm indicators, commitment signals, and provides honest guidance. The Reply Suggestions mode can generate responses in different tones appropriate for the relationship context you specify.",
  },
  {
    question: "Does it work offline?",
    answer: "Yes! After the first use, the AI model is cached in your browser. Once downloaded, you can analyze messages without an internet connection. Your analysis history is saved locally so you can review past analyses anytime.",
  },
  {
    question: "Can I use the quick example messages?",
    answer: "Yes. We provide 4 sample messages (dating text, work email, suspicious message, cold response) that you can load with one click to see how the tool works before pasting your own messages. There are also quick presets like 'Dating Message' and 'Work Email' that auto-select the most relevant analysis options.",
  },
];

export const defaultToolFAQs: FAQItem[] = [
  {
    question: "Is this AI tool really free?",
    answer: "Yes, all Browser AI Tools are completely free. The AI runs locally in your browser, so there are no server costs. No subscriptions, no hidden fees, no usage limits.",
  },
  {
    question: "How does browser-based AI work?",
    answer: "We use WebLLM technology to run AI models directly in your browser using WebGPU. This means your data never leaves your device - everything is processed locally for maximum privacy.",
  },
  {
    question: "What browsers are supported?",
    answer: "You need a browser with WebGPU support: Google Chrome 113+, Microsoft Edge 113+, or Safari 18+ with WebGPU flags enabled. We recommend the latest version of Chrome or Edge for the best experience.",
  },
  {
    question: "Does this tool work offline?",
    answer: "Yes! After the AI model is downloaded on first use, it's cached in your browser. You can then use the tool without an internet connection.",
  },
  {
    question: "Is my data private?",
    answer: "Absolutely. Unlike cloud-based AI tools, Browser AI Tools runs 100% locally in your browser. Your inputs and outputs never leave your device. No servers, no tracking, no data collection.",
  },
];

export const explainThisFAQs: FAQItem[] = [
  {
    question: "What types of text can this tool explain?",
    answer: "Virtually anything -- academic textbooks, legal contracts, medical reports, technical documentation, scientific papers, news articles, business documents, terms of service, privacy policies, code, and more. If text confuses you, paste it in and get a clear explanation.",
  },
  {
    question: "Is my pasted text kept private?",
    answer: "Yes, 100%. The AI model runs entirely in your browser using WebLLM technology. Your text is never uploaded to any server, never stored remotely, and never seen by anyone. This makes it safe for sensitive content like medical records, legal documents, or work emails.",
  },
  {
    question: "What are the different explanation modes?",
    answer: "There are six modes: Simple Explanation (everyday language), ELI5 / Explain Like I'm 5 (extremely simple), Step-by-Step (sequential breakdown), Analogy (real-world comparisons), Technical (precise detail for those with some background), and Academic (scholarly with formal terminology). You can select multiple modes at once.",
  },
  {
    question: "How does the reading level slider work?",
    answer: "The slider adjusts how complex the explanation's vocabulary and sentence structure will be. Grade 5 produces very basic language suitable for children, while PhD produces advanced language suitable for experts. The default is Grade 10 (high school level), which works well for most people.",
  },
  {
    question: "What does the subject area setting do?",
    answer: "It helps the AI tailor its explanation to a specific domain. For example, selecting 'Legal' will make the AI focus on translating legalese and explaining practical implications, while 'Medical' will ensure patient-friendly language and term definitions. 'Auto-Detect' lets the AI figure out the subject automatically.",
  },
  {
    question: "Can I use this for homework or studying?",
    answer: "Absolutely. Students use this tool to understand textbook passages, research papers, and complex assignments. The ELI5 and Step-by-Step modes are especially helpful for building foundational understanding, while the Academic mode helps prepare for exams.",
  },
  {
    question: "Does the tool work offline?",
    answer: "Yes. After the AI model is downloaded on first use, it is cached in your browser. You can then use the tool without an internet connection -- perfect for studying on the go or working in areas with limited connectivity.",
  },
  {
    question: "What browsers are supported?",
    answer: "You need a browser with WebGPU support: Google Chrome 113+, Microsoft Edge 113+, or Safari 18+ with WebGPU flags enabled. We recommend the latest version of Chrome or Edge for the best experience.",
  },
];

export const essayWriterFAQs: FAQItem[] = [
  {
    question: "What types of essays can this tool generate?",
    answer: "The AI Essay Writer supports six essay types: Argumentative (defend a position with evidence), Expository (explain a topic clearly), Narrative (tell a compelling story), Descriptive (paint a vivid picture), Compare & Contrast (analyze similarities and differences), and Persuasive (convince the reader). Each type uses a distinct structure and approach appropriate to the format.",
  },
  {
    question: "How does the academic level setting work?",
    answer: "You can choose from five academic levels: High School, College, University, Master's, and PhD. The AI adjusts vocabulary complexity, argument depth, source sophistication, and analytical rigor to match the selected level. A high school essay uses straightforward language, while a PhD-level essay employs nuanced academic discourse and advanced theoretical frameworks.",
  },
  {
    question: "Does the tool format citations properly?",
    answer: "Yes. You can select from APA 7th Edition, MLA 9th Edition, Chicago, Harvard, or no citations. The AI generates properly formatted in-text citations and a references section that follows the conventions of your chosen style. Note that references are illustrative examples -- always verify citations against actual sources for academic submissions.",
  },
  {
    question: "Is my essay topic and content private?",
    answer: "Absolutely. The AI model runs entirely in your browser using WebLLM technology. Your essay topic, requirements, and the generated content never leave your device. No data is uploaded to any server, making it safe for sensitive academic work.",
  },
  {
    question: "What is Outline-Only mode?",
    answer: "Outline-Only mode generates a structured essay outline instead of a full essay. It includes the thesis statement, main arguments, supporting points, and conclusion framework -- perfect for planning your essay before writing, or for submitting an outline as part of a multi-stage assignment.",
  },
  {
    question: "How accurate is the word count control?",
    answer: "You can set a target word count between 500 and 5,000 words. The AI aims to match your target closely, though the actual count may vary by 10-15% depending on the complexity of the topic and the essay type. The final word count is displayed in the output stats.",
  },
  {
    question: "Can I use this for academic work?",
    answer: "This tool is designed as a writing assistant to help you understand essay structure, generate ideas, and learn effective argumentation techniques. Always follow your institution's academic integrity policies. We recommend using the generated essays as a starting point and adding your own research, analysis, and voice.",
  },
  {
    question: "Does the tool work offline?",
    answer: "Yes. After the AI model is downloaded on first use, it is cached in your browser. You can then generate essays without an internet connection -- great for studying or writing on the go.",
  },
];

export const datingProfileFAQs: FAQItem[] = [
  {
    question: "Which dating apps does this work for?",
    answer: "The generator is optimized for the three most popular dating apps: Tinder, Bumble, and Hinge. You can select one or multiple apps, and the AI tailors your bio, prompt answers, and opening lines to match each app's style and character limits.",
  },
  {
    question: "Is my personal information kept private?",
    answer: "Absolutely. The AI model runs entirely in your browser using WebLLM technology. Your age, interests, photos, and generated profiles never leave your device. No data is uploaded to any server -- perfect for keeping your dating life private.",
  },
  {
    question: "What are the vibe options?",
    answer: "You can choose from six personality vibes: Funny & Playful (humor-forward), Flirty & Confident (bold and direct), Deep & Thoughtful (intellectual and genuine), Adventurous & Active (outdoorsy and energetic), Chill & Easygoing (relaxed and approachable), and Professional but Fun (polished yet personable). The AI adapts your entire profile to match your chosen vibe.",
  },
  {
    question: "Does it generate opening messages too?",
    answer: "Yes! When the opening lines toggle is enabled, the AI generates 5-7 conversation starters tailored to your vibe and the apps you selected. These are designed to stand out and get responses -- not generic 'hey' messages.",
  },
  {
    question: "Can I generate photo captions?",
    answer: "Yes. Describe your photos (e.g., 'hiking pic with mountain view', 'cooking in the kitchen', 'at a music festival') and the AI will generate witty, engaging captions that match your profile vibe. Just enable the photo captions toggle and fill in the photo descriptions.",
  },
  {
    question: "How do I get the best results?",
    answer: "Be specific about your interests and hobbies, choose a vibe that genuinely matches your personality, and include details about what you are looking for. The more context you give the AI, the more authentic and personalized your profile will be. Try generating 2-3 versions and mix the best parts.",
  },
  {
    question: "Can I customize the tone separately from the vibe?",
    answer: "Yes. The vibe sets your overall personality style, while the tone fine-tunes how the text reads: Funny (humor-driven), Flirty (playful and suggestive), Witty (clever and sharp), or Genuine (sincere and straightforward). Combining different vibes and tones lets you find the perfect voice.",
  },
  {
    question: "Does the tool work offline?",
    answer: "Yes. After the AI model is downloaded on first use, it is cached in your browser. You can generate profiles and openers without an internet connection.",
  },
];
