import { StoryHero } from "@/components/StoryHero";
import { StoryGenerator } from "@/components/StoryGenerator";
import { StoryArticle } from "@/components/StoryArticle";
import { ToolPageHeader } from "@/components/ToolPageHeader";
import { ToolFAQ } from "@/components/ToolFAQ";
import { AdBlock } from "@/components/AdBlock";
import ToolSchema from "@/components/ToolSchema";
import RelatedTools from "@/components/RelatedTools";
import { storyStarterFAQs } from "@/lib/faqs-data";
import { BookOpenCheck } from "lucide-react";
import { motion } from "framer-motion";
import { useEffect } from "react";

export default function StoryStarterPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
    document.title = "Free AI Story Starter - Spark Your Next Novel Instantly | Browser AI Tools";

    const metaUpdates: Record<string, string> = {
      description: "AI-powered story starter generator. Get 5 powerful opening lines tailored to your genre and tone. Fantasy, horror, sci-fi, romance, mystery, and more. 100% private and free.",
    };
    const ogUpdates: Record<string, string> = {
      "og:title": "Free AI Story Starter - Spark Your Next Novel Instantly | Browser AI Tools",
      "og:description": "Overcome writer's block instantly. 5 genre-perfect story opening lines generated by AI. 100% private, runs in your browser.",
      "og:type": "website",
      "og:url": "https://browseraitools.com/ai-story-starter",
    };

    for (const [name, content] of Object.entries(metaUpdates)) {
      let tag = document.querySelector(`meta[name="${name}"]`);
      if (!tag) { tag = document.createElement("meta"); tag.setAttribute("name", name); document.head.appendChild(tag); }
      tag.setAttribute("content", content);
    }
    for (const [property, content] of Object.entries(ogUpdates)) {
      let tag = document.querySelector(`meta[property="${property}"]`);
      if (!tag) { tag = document.createElement("meta"); tag.setAttribute("property", property); document.head.appendChild(tag); }
      tag.setAttribute("content", content);
    }
  }, []);

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebApplication",
            "name": "AI Story Starter",
            "applicationCategory": "UtilitiesApplication",
            "offers": { "@type": "Offer", "price": "0" },
            "description": "AI-powered story starter generator that creates 5 powerful opening lines tailored to your genre and tone. 100% private, runs locally in your browser.",
          }),
        }}
      />

      <ToolPageHeader toolName="AI Story Starter" icon={BookOpenCheck} />

      <div className="pb-12">
        <StoryHero />
        <AdBlock slot="story-top" format="horizontal" className="mb-8" />
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
        >
          <StoryGenerator />
        </motion.div>
      </div>

      <AdBlock slot="story-mid" format="horizontal" className="mb-10" />

      <StoryArticle />

      <ToolFAQ toolName="AI Story Starter" faqs={storyStarterFAQs} />

      <AdBlock slot="story-bottom" format="horizontal" className="mt-10" />
    
      <ToolSchema faqs={storyStarterFAQs} toolName="AI Story Starter" toolDescription="AI-powered story starter generator. Get 5 powerful opening lines tailored to your genre and tone. Fantasy, horror, sci-fi, romance, mystery, and more. 100% p..." category="EntertainmentApplication" />

      <RelatedTools currentToolName="AI Story Starter" currentCategory="EntertainmentApplication" />
    </>
  );
}
