import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";
import { motion, AnimatePresence } from "framer-motion";

export function FAQGeneratorArticle() {
  return (
    <section className="max-w-4xl mx-auto px-4 sm:px-6 py-12">
      <div className="prose prose-slate max-w-none">
        <h2 className="text-2xl md:text-3xl font-display font-bold text-slate-900 mb-6">
          How to Create Effective FAQs for Your Website
        </h2>

        <ArticleSection title="Why FAQs Matter for SEO">
          <p>FAQ sections are one of the most powerful yet underutilized SEO tools. Google actively looks for FAQ content and can display it directly in search results as rich snippets, dramatically increasing your visibility and click-through rates.</p>
          <p>Websites with properly structured FAQ sections see an average 15-25% increase in organic traffic. The key is writing questions that match how real people search, using natural language patterns that align with voice search and long-tail keywords.</p>
          <div className="bg-purple-50 border-l-4 border-purple-400 p-4 rounded-r-lg my-4">
            <p className="text-purple-800 mb-0 text-sm"><strong>Key Insight:</strong> Pages with FAQ schema markup are 2-3x more likely to appear in Google's "People Also Ask" boxes, which can drive significant additional traffic.</p>
          </div>
        </ArticleSection>

        <ArticleSection title="Writing Questions That Rank">
          <p>The best FAQ questions mirror how people actually search. Start questions with interrogative words like "What," "How," "Why," "Can," and "Does." These match the natural language patterns used in both typed and voice searches.</p>
          <ul className="space-y-2 text-slate-600">
            <li><strong className="text-slate-800">Use specific questions:</strong> "What are the benefits of solar panels for homes?" ranks better than "Solar panel benefits."</li>
            <li><strong className="text-slate-800">Cover different intents:</strong> Include informational (what/why), navigational (where/how to find), and transactional (how much/can I buy) questions.</li>
            <li><strong className="text-slate-800">Answer directly first:</strong> Start each answer with a clear, direct response before adding context. Google often pulls the first sentence for featured snippets.</li>
            <li><strong className="text-slate-800">Keep answers focused:</strong> Each answer should address exactly one concept. If an answer needs multiple paragraphs, consider splitting it into separate questions.</li>
          </ul>
        </ArticleSection>

        <ArticleSection title="FAQ Schema Markup Explained">
          <p>FAQ schema markup is structured data code (JSON-LD format) that tells search engines your page contains frequently asked questions. When implemented correctly, Google can display your FAQs directly in search results.</p>
          <h4 className="font-bold text-slate-800 mt-4">How to implement:</h4>
          <ul className="space-y-2 text-slate-600">
            <li><strong className="text-slate-800">Copy the JSON-LD code</strong> generated by this tool after creating your FAQs.</li>
            <li><strong className="text-slate-800">Add it to your page</strong> inside a script tag in the head section of your HTML.</li>
            <li><strong className="text-slate-800">Validate with Google</strong> using the Rich Results Test tool to ensure proper formatting.</li>
            <li><strong className="text-slate-800">Monitor in Search Console</strong> to track how your FAQ rich results perform.</li>
          </ul>
          <div className="bg-purple-50 border-l-4 border-purple-400 p-4 rounded-r-lg my-4">
            <p className="text-purple-800 mb-0 text-sm"><strong>Important:</strong> Google requires that FAQ schema content matches what is visible on the page. Do not use schema for content that is hidden or only shown in modals.</p>
          </div>
        </ArticleSection>

        <ArticleSection title="How Many FAQs Should You Have">
          <p>The ideal number depends on your use case:</p>
          <ul className="space-y-2 text-slate-600">
            <li><strong className="text-slate-800">Landing pages:</strong> 5-7 questions focused on objection handling and product clarity.</li>
            <li><strong className="text-slate-800">Blog posts:</strong> 5-10 questions that expand on the article topic and target related long-tail keywords.</li>
            <li><strong className="text-slate-800">Product pages:</strong> 8-15 questions covering specifications, shipping, returns, and common concerns.</li>
            <li><strong className="text-slate-800">Help centers:</strong> 15-20+ questions organized by category for comprehensive support coverage.</li>
          </ul>
          <p>For schema markup specifically, Google recommends keeping it under 10 questions per page to avoid triggering spam filters.</p>
        </ArticleSection>

        <ArticleSection title="Best Practices for FAQ Answers">
          <ul className="space-y-2 text-slate-600">
            <li><strong className="text-slate-800">Lead with the answer:</strong> Put the most important information first. Many readers scan only the first line.</li>
            <li><strong className="text-slate-800">Use 2-4 sentences:</strong> Long enough to be helpful, short enough to be scannable. Detailed answers should not exceed one paragraph.</li>
            <li><strong className="text-slate-800">Include keywords naturally:</strong> Work relevant search terms into answers without keyword stuffing. Write for humans first.</li>
            <li><strong className="text-slate-800">Add internal links:</strong> Where appropriate, link to relevant pages on your site for deeper information.</li>
            <li><strong className="text-slate-800">Update regularly:</strong> Review FAQs quarterly to ensure answers remain accurate and reflect current offerings.</li>
          </ul>
        </ArticleSection>
      </div>
    </section>
  );
}

function ArticleSection({ title, children }: { title: string; children: React.ReactNode }) {
  const [open, setOpen] = useState(false);
  const panelId = `faq-article-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
  return (
    <div className="border-b border-slate-200 py-4">
      <button type="button" onClick={() => setOpen(!open)} className="w-full flex items-center justify-between text-left group" data-testid={`button-article-section-${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`} aria-expanded={open} aria-controls={panelId}>
        <h3 className="text-lg font-bold text-slate-800 group-hover:text-purple-700 transition-colors">{title}</h3>
        <ChevronDown className={cn("w-5 h-5 text-slate-400 transition-transform shrink-0 ml-4", open && "rotate-180")} />
      </button>
      <AnimatePresence>
        {open && (
          <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: "auto", opacity: 1 }} exit={{ height: 0, opacity: 0 }} transition={{ duration: 0.2 }} className="overflow-hidden">
            <div id={panelId} className="pt-4 text-slate-600 text-[15px] leading-relaxed space-y-3">{children}</div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
